# Generated by Django 5.0.2 on 2024-04-22 23:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AssessmentQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('answer', models.TextField()),
                ('support', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='AssessmentTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('assessment_type', models.CharField(max_length=255)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('primary_location', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email_address', models.EmailField(max_length=254)),
                ('security_group', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Assessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('percent_complete', models.DecimalField(decimal_places=2, max_digits=5)),
                ('comments', models.TextField()),
                ('status', models.CharField(max_length=255)),
                ('site_location', models.CharField(max_length=255)),
                ('assessment_template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AssessmentAPI.assessmenttemplate')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AssessmentAPI.customer')),
                ('alignment_engineer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AssessmentAPI.user')),
            ],
        ),
        migrations.CreateModel(
            name='ProposedProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('completion_date', models.DateField()),
                ('description', models.TextField()),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AssessmentAPI.customer')),
            ],
        ),
        migrations.CreateModel(
            name='Recommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('completion_date', models.DateField()),
                ('description', models.TextField()),
                ('status', models.CharField(max_length=255)),
                ('priority', models.IntegerField()),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AssessmentAPI.assessment')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AssessmentAPI.customer')),
            ],
        ),
        migrations.CreateModel(
            name='RecommendationProposedProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proposed_project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AssessmentAPI.proposedproject')),
                ('recommendation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AssessmentAPI.recommendation')),
            ],
        ),
        migrations.CreateModel(
            name='TechnologyInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_name', models.CharField(max_length=255)),
                ('site_location', models.CharField(max_length=255)),
                ('type', models.CharField(max_length=255)),
                ('make', models.CharField(max_length=255)),
                ('model', models.CharField(max_length=255)),
                ('serial_number', models.CharField(max_length=255)),
                ('operating_system', models.CharField(max_length=255)),
                ('date_purchased', models.DateField()),
                ('date_warranty_expired', models.DateField()),
                ('age_years', models.IntegerField()),
                ('date_last_updated', models.DateField()),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AssessmentAPI.customer')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=255)),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField()),
                ('completion_date', models.DateField()),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AssessmentAPI.customer')),
                ('project_manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AssessmentAPI.user')),
            ],
        ),
        migrations.AddField(
            model_name='customer',
            name='alignment_engineer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alignment_engineered_customers', to='AssessmentAPI.user'),
        ),
        migrations.AddField(
            model_name='customer',
            name='vcio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vcio_customers', to='AssessmentAPI.user'),
        ),
    ]
